<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\TakeABreak.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\TakeABreak.ico" />
    <None Remove="Images\tpb.jpeg" />
    <None Remove="Images\usdt.jpeg" />
    <None Remove="View\tpb.jpeg" />
    <None Remove="View\usdt.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\TakeABreak.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PipeCS\PipeCS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\tpb.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\usdt.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\tpb.jpeg" />
    <Resource Include="View\usdt.jpeg" />
  </ItemGroup>

</Project>
